export type Theme = 'light' | 'dark'

export type NavPage = 'dashboard' | 'campaigns' | 'connections' | 'assignments' | 'deals' | 'feedback' | 'profile' | 'raise-ticket' | 'my-tickets' | 'notifications'

export * from './CampaignTypes'
export * from './DealTypes'
export * from './PlatformTypes'
export * from './ConnectionTypes'
export * from './RegisterTypes'
export * from './LoginTypes'
export * from './ForgotPasswordTypes'
export * from './ProfileTypes'
export * from './TicketTypes'
export * from './AssignmentTypes'
export * from './NotificationTypes'
