ALTER TABLE campaigns ALTER COLUMN code TYPE VARCHAR(16);
ALTER TABLE deals ALTER COLUMN code TYPE VARCHAR(16);
ALTER TABLE claims ALTER COLUMN code TYPE VARCHAR(16);
ALTER TABLE tickets ALTER COLUMN code TYPE VARCHAR(16);
ALTER TABLE users ALTER COLUMN code TYPE VARCHAR(16);