package com.coddicted.buzzma.claim.entity;

public enum ClaimStatus {
  CREATED,
  REDIRECTED,
  ORDERED,
  PROOF_SUBMITTED,
  UNDER_REVIEW,
  ADDITIONAL_PROOF_REQUESTED,
  APPROVED,
  REJECTED,
  REWARD_PENDING,
  COMPLETED,
  FAILED
}
