package com.coddicted.buzzma.claim.entity;

public enum ClaimReviewStatus {
  CLAIM_REVIEW_STATUS_PENDING,
  CLAIM_REVIEW_STATUS_PROOF_REQUESTED,
  CLAIM_REVIEW_STATUS_OBJECTED,
  CLAIM_REVIEW_STATUS_APPROVED,
  CLAIM_REVIEW_STATUS_REJECTED
}
