services:
  communications:
    build: .
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: api
    ports:
      - "8083:8083"

  communications-worker:
    build: .
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: worker
