package com.coddicted.buzzma.shared.common;

public final class CodeGenerator {

  public static final CodeGenerator INSTANCE = new CodeGenerator();

  private CodeGenerator() {}

  private static final int MIN_CODE_LENGTH = 4;
  private static final int MAX_CODE_LENGTH = 10;

  private static final String SAFE_CHARS = "X3NKBHP2MZTJ4RCFQ8YVGW5ADSE76UL9";

  /**
   * Generate unique code for a given value and given length deterministically. The code is
   * generated by scrambling the value and then encoding it using a custom base32 encoding with the
   * provided safe characters. The code will have a hyphen after every 4th character for better
   * readability.
   *
   * @param value value
   * @param length length of the generated code, should be between 4 and 10 (inclusive)
   * @return Alphanumeric code
   */
  public String generateCode(final long value, final int length) {
    validateLength(length);
    long num = scramble(value);
    final StringBuilder result = new StringBuilder();
    for (int i = 0; i < length; i++) {
      result.insert(0, SAFE_CHARS.charAt((int) (num % 32)));
      num /= 32;
    }
    return hyphenate(result.toString());
  }

  private static void validateLength(final int length) {
    if (length < MIN_CODE_LENGTH || length > MAX_CODE_LENGTH) {
      throw new IllegalArgumentException(
          "length must be between "
              + MIN_CODE_LENGTH
              + " and "
              + MAX_CODE_LENGTH
              + ", got "
              + length);
    }
  }

  private static long scramble(long n) {
    n = ((n >>> 16) ^ n) * 0x45d9f3bL;
    n = ((n >>> 16) ^ n) * 0x45d9f3bL;
    n = (n >>> 16) ^ n;
    return Math.abs(n);
  }

  private static String hyphenate(final String code) {
    final StringBuilder result = new StringBuilder(code);
    for (int pos = 4; pos < result.length(); pos += 5) {
      result.insert(pos, '-');
    }
    return result.toString();
  }
}
